---
name: CI

on: push
  # pull_request:
  # schedule:
  #   - cron: '4 4 * * *'


concurrency:
  group: ${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  puppet:
    name: Puppet
    uses: voxpupuli/gha-puppet/.github/workflows/beaker.yml@v1
    with:
      pidfile_workaround: 'CentOS'
      rubocop: false
      cache-version: '1'
